name = "BandwidthBenchmark"
uuid = "68eb07c1-04fd-4e62-9736-d6127c4c03c6"
authors = ["Carsten Bauer <crstnbr@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
